[package]
name = "libm_capi"
version = "0.1.0"
authors = [ "David Wood <devel@dtwood.uk>" ]

[lib]
name = "libm_capi"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"

[dependencies.libm]
path = "../"
